version: '3'

services:
  webserver:
    build: 
      context: ./webserver
      dockerfile: Dockerfile
    container_name: webserver_container
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ./webfiles:/var/www/html
      - ./configfiles/nginx.conf:/etc/nginx/nginx.conf
      - ./configfiles/php.ini:/etc/php8/php.ini
      - ./configfiles/www.conf:/etc/php8/php-fpm.d/www.conf
      - ./configfiles/php-fpm.conf:/etc/php8/php-fpm.conf
    command: ["/docker-entrypoint.sh"]
    networks:
      csvs_network:
        ipv4_address: 203.0.113.200
    extra_hosts:
      - "db.cyber23.test:203.0.113.201"
    restart: unless-stopped
    depends_on:
      - dbserver

  dbserver:
    image: u5529680_csvs_dbserver_i
    volumes:
      - /home/kali/Desktop/CSVS_PMA_24/dbserver/mysqld.cnf:/etc/mysql/mysql.config/mysqld.cnf
      - /home/kali/Desktop/CSVS_PMA_24/dbserver/sqlconfig:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    build:
      context: /home/kali/Desktop/CSVS_PMA_24/dbserver
      dockerfile: Dockerfile
    container_name: u5529680_csvs_dbserver_c
    environment:
      MYSQL_ROOT_PASSWORD: "CorrectHorseBatteryStaple"
      MYSQL_DATABASE: "csvs23db"
    networks:
      csvs_network:
        ipv4_address: 203.0.113.201
    hostname: db.cyber23.test
    privileged: true
networks:
  csvs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 203.0.113.0/24
